web:
  build: web
  volumes:
    - data/logs/nginx:/var/log/nginx
    - data/static:/usr/share/nginx/html:ro
  ports:
    - "80:80"
  links:
    - app
app:
  build: app
  volumes:
    - app:/usr/src/app
    - data/logs/app:/usr/src/app/logs
    - data/static:/usr/src/app/static
  ports:
    - "8000:8000"
  links:
    - db
    - amqp
  environment:
    DATABASE_URL: postgres://postgres@db/postgres
    BROKER_URL: amqp://guest:guest@amqp/
    DEBUG: True
db:
  image: postgres
  volumes_from:
    - dbdata
  ports:
    - "5432"
dbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: true
amqp:
  image: rabbitmq
  volumes_from:
    - amqpdata
  ports:
    - "5672"
amqpdata:
  image: rabbitmq
  volumes:
    - /var/lib/rabbitmq
  command: true
