web:
  build: web
  volumes:
    - log/nginx:/var/log/nginx
    - data/static:/usr/share/nginx/html:ro
  ports:
    - "80:80"
  links:
    - app
app:
  build: app
  volumes:
    - app:/usr/src/app
    - log/app:/usr/src/app/logs
    - data/static:/usr/src/app/static
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    DATABASE_URL: postgres://postgres@db/postgres
    DEBUG: True
db:
  image: postgres
  volumes_from:
    - dbdata
  ports:
    - "5432"
dbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: true
