web:
  build: web
  volumes:
    - data/logs/nginx:/var/log/nginx
    - data/static:/usr/share/nginx/html:ro
  ports:
    - "80:80"
  links:
    - app
app:
  build: app
  volumes:
    - app:/usr/src/app
    - data/logs/app:/usr/src/app/logs
    - data/static:/usr/src/app/static
  expose:
    - "8000"
  links:
    - db
    - amqp
    - sentry
  environment:
    BROKER_URL: amqp://guest:guest@amqp/
    DATABASE_URL: postgres://postgres@db/postgres
    DEBUG: True
  env_file:
    - conf/app.env
db:
  image: postgres
  volumes_from:
    - dbdata
  expose:
    - "5432"
dbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: true
amqp:
  image: rabbitmq:management
  volumes_from:
    - amqpdata
  expose:
    - "5672"
    - "15672"
amqpdata:
  image: rabbitmq
  volumes:
    - /var/lib/rabbitmq
  command: true
flower:
  image: nicholsn/docker-flower
  links:
    - amqp:mq
  ports:
    - "5555:5555"
sentrydb:
  image: postgres
  volumes_from:
    - sentrydbdata
  expose:
    - "5432"
sentrydbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: true
sentryredis:
  image: redis
  volumes_from:
    - sentryredisdata
  expose:
    - "6379"
sentryredisdata:
  image: redis
  volumes:
    - data/sentryredis:/data
  command: true
sentry:
  image: slafs/sentry
  volumes:
    - data/sentry:/data
  links:
    - sentrydb
    - sentryredis:redis
  ports:
    - "9000:9000"
  environment:
    CACHE_URL: hiredis://redis:6379/2/
    DATABASE_URL: postgres://postgres@sentrydb/postgres
    SENTRY_URL_PREFIX: http://localhost:9000
  env_file:
    - conf/sentry.env
